// <auto-generated />
using System;
using Hospital.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospital.EntityFramework.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hospital.Domain.Model.Belay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Belays");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Change", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSpan")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffId");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("_Adress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TitleId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DepartmentTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentTitles");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DiagnosisGroupId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DiagnosisClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiagnosisClasses");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DiagnosisGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisClassId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisClassId");

                    b.ToTable("DiagnosisGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DrugForm")
                        .HasColumnType("int");

                    b.Property<int?>("DrugSubGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Substance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrugSubGroupId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DrugClasses");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrugSubClassId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrugSubClassId");

                    b.ToTable("DrugGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugSubClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DrugClassId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrugClassId");

                    b.ToTable("DrugSubClasses");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrugGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReciept")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrugGroupId");

                    b.ToTable("DrugSubGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorDestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("EntryOutId")
                        .HasColumnType("int");

                    b.Property<int>("EntryStatus")
                        .HasColumnType("int");

                    b.Property<int>("InviteStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MedCardId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistratorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDestinationId");

                    b.HasIndex("EntryOutId");

                    b.HasIndex("MedCardId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RegistratorId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Hospital.Domain.Model.MedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiagnosisDoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDifferential")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreliminary")
                        .HasColumnType("bit");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Recomendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TherapyDoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisDoctorId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TherapyDoctorId");

                    b.ToTable("MedCards");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BelayCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BelayDateOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BelayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("HasChild")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMarried")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("bigint");

                    b.Property<string>("_Adress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adress");

                    b.HasKey("Id");

                    b.HasIndex("BelayId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PharmacoTherapyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiagnosisDoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrugId")
                        .HasColumnType("int");

                    b.Property<int?>("MedCardId")
                        .HasColumnType("int");

                    b.Property<int?>("TherapyDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Trademark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Treatment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisDoctorId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("DrugId");

                    b.HasIndex("MedCardId");

                    b.HasIndex("TherapyDoctorId");

                    b.ToTable("PharmacoTherapyDatas");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysTherFactGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhysTherFactGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysTherMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhysTherMethodGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhysTherMethodGroupId");

                    b.ToTable("PhysTherMethods");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysTherMethodGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhysTherMethodGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysioTherapyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiagnosisDoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Localization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedCardId")
                        .HasColumnType("int");

                    b.Property<int?>("OperationDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhysTherMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("PhysioTherapyFactorId")
                        .HasColumnType("int");

                    b.Property<int>("ProcedureStatus")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RemainingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("TargetDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TherapyDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Treatment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisDoctorId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("MedCardId");

                    b.HasIndex("OperationDoctorId");

                    b.HasIndex("PhysTherMethodId");

                    b.HasIndex("PhysioTherapyFactorId");

                    b.HasIndex("TherapyDoctorId");

                    b.ToTable("PhysioTherapyDatas");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysioTherapyFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhysTherFactGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tool")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhysTherFactGroupId");

                    b.ToTable("PhysioTherapyFactors");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cabinet")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MidName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("bigint");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("WeekDays")
                        .HasColumnType("int");

                    b.Property<string>("_Adress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adress");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Hospital.Domain.Model.SurgeryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SurgeryType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurgeryGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.SurgeryOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SurgeryGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SurgeryGroupId");

                    b.ToTable("SurgeryOperations");
                });

            modelBuilder.Entity("Hospital.Domain.Model.SurgeryTherapyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiagnosisDoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<int?>("MedCardId")
                        .HasColumnType("int");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcedureStatus")
                        .HasColumnType("int");

                    b.Property<int>("SurgeryClass")
                        .HasColumnType("int");

                    b.Property<int?>("SurgeryOperationId")
                        .HasColumnType("int");

                    b.Property<int>("SurgeryPriority")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TherapyDoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisDoctorId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("MedCardId");

                    b.HasIndex("SurgeryOperationId");

                    b.HasIndex("TherapyDoctorId");

                    b.ToTable("SurgeryTherapyDatas");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestTypeId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateResult")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSymptom")
                        .HasColumnType("bit");

                    b.Property<int?>("MedCardId")
                        .HasColumnType("int");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffResultId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedCardId");

                    b.HasIndex("StaffResultId");

                    b.HasIndex("TestId");

                    b.ToTable("TestDatas");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestNormalValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeIn")
                        .HasColumnType("int");

                    b.Property<int>("AgeOut")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestNormalValues");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("JsonObjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("TestTemplates");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("TestMethod")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Change", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Department", null)
                        .WithMany("Changes")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Hospital.Domain.Model.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Department", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Staff", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("Hospital.Domain.Model.DepartmentTitle", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId");

                    b.Navigation("Manager");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Diagnosis", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Department", "Department")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Hospital.Domain.Model.DiagnosisGroup", "DiagnosisGroup")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DiagnosisGroupId");

                    b.Navigation("Department");

                    b.Navigation("DiagnosisGroup");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DiagnosisGroup", b =>
                {
                    b.HasOne("Hospital.Domain.Model.DiagnosisClass", "DiagnosisClass")
                        .WithMany("DiagnosisGroups")
                        .HasForeignKey("DiagnosisClassId");

                    b.Navigation("DiagnosisClass");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Drug", b =>
                {
                    b.HasOne("Hospital.Domain.Model.DrugSubGroup", "DrugSubGroup")
                        .WithMany("Drugs")
                        .HasForeignKey("DrugSubGroupId");

                    b.Navigation("DrugSubGroup");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugGroup", b =>
                {
                    b.HasOne("Hospital.Domain.Model.DrugSubClass", "DrugSubClass")
                        .WithMany("DrugGroups")
                        .HasForeignKey("DrugSubClassId");

                    b.Navigation("DrugSubClass");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugSubClass", b =>
                {
                    b.HasOne("Hospital.Domain.Model.DrugClass", "DrugClass")
                        .WithMany("DrugSubClasses")
                        .HasForeignKey("DrugClassId");

                    b.Navigation("DrugClass");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugSubGroup", b =>
                {
                    b.HasOne("Hospital.Domain.Model.DrugGroup", "DrugGroup")
                        .WithMany("DrugSubGroups")
                        .HasForeignKey("DrugGroupId");

                    b.Navigation("DrugGroup");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Entry", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Staff", "DoctorDestination")
                        .WithMany("DoctorDestinations")
                        .HasForeignKey("DoctorDestinationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Hospital.Domain.Model.Entry", "EntryOut")
                        .WithMany()
                        .HasForeignKey("EntryOutId");

                    b.HasOne("Hospital.Domain.Model.MedCard", "MedCard")
                        .WithMany()
                        .HasForeignKey("MedCardId");

                    b.HasOne("Hospital.Domain.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("Hospital.Domain.Model.Staff", "Registrator")
                        .WithMany("Registrators")
                        .HasForeignKey("RegistratorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DoctorDestination");

                    b.Navigation("EntryOut");

                    b.Navigation("MedCard");

                    b.Navigation("Patient");

                    b.Navigation("Registrator");
                });

            modelBuilder.Entity("Hospital.Domain.Model.MedCard", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Staff", "DiagnosisDoctor")
                        .WithMany()
                        .HasForeignKey("DiagnosisDoctorId");

                    b.HasOne("Hospital.Domain.Model.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("Hospital.Domain.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("Hospital.Domain.Model.Staff", "TherapyDoctor")
                        .WithMany()
                        .HasForeignKey("TherapyDoctorId");

                    b.Navigation("Diagnosis");

                    b.Navigation("DiagnosisDoctor");

                    b.Navigation("Patient");

                    b.Navigation("TherapyDoctor");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Patient", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Belay", "Belay")
                        .WithMany()
                        .HasForeignKey("BelayId");

                    b.Navigation("Belay");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PharmacoTherapyData", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Staff", "DiagnosisDoctor")
                        .WithMany()
                        .HasForeignKey("DiagnosisDoctorId");

                    b.HasOne("Hospital.Domain.Model.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("Hospital.Domain.Model.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId");

                    b.HasOne("Hospital.Domain.Model.MedCard", "MedCard")
                        .WithMany("PharmacoTherapyDatas")
                        .HasForeignKey("MedCardId");

                    b.HasOne("Hospital.Domain.Model.Staff", "TherapyDoctor")
                        .WithMany()
                        .HasForeignKey("TherapyDoctorId");

                    b.Navigation("Diagnosis");

                    b.Navigation("DiagnosisDoctor");

                    b.Navigation("Drug");

                    b.Navigation("MedCard");

                    b.Navigation("TherapyDoctor");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysTherMethod", b =>
                {
                    b.HasOne("Hospital.Domain.Model.PhysTherMethodGroup", "PhysTherMethodGroup")
                        .WithMany("PhysTherMethods")
                        .HasForeignKey("PhysTherMethodGroupId");

                    b.Navigation("PhysTherMethodGroup");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysioTherapyData", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Staff", "DiagnosisDoctor")
                        .WithMany()
                        .HasForeignKey("DiagnosisDoctorId");

                    b.HasOne("Hospital.Domain.Model.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("Hospital.Domain.Model.MedCard", "MedCard")
                        .WithMany("PhysioTherapyDatas")
                        .HasForeignKey("MedCardId");

                    b.HasOne("Hospital.Domain.Model.Staff", "OperationDoctor")
                        .WithMany()
                        .HasForeignKey("OperationDoctorId");

                    b.HasOne("Hospital.Domain.Model.PhysTherMethod", "PhysTherMethod")
                        .WithMany()
                        .HasForeignKey("PhysTherMethodId");

                    b.HasOne("Hospital.Domain.Model.PhysioTherapyFactor", "PhysioTherapyFactor")
                        .WithMany()
                        .HasForeignKey("PhysioTherapyFactorId");

                    b.HasOne("Hospital.Domain.Model.Staff", "TherapyDoctor")
                        .WithMany()
                        .HasForeignKey("TherapyDoctorId");

                    b.Navigation("Diagnosis");

                    b.Navigation("DiagnosisDoctor");

                    b.Navigation("MedCard");

                    b.Navigation("OperationDoctor");

                    b.Navigation("PhysioTherapyFactor");

                    b.Navigation("PhysTherMethod");

                    b.Navigation("TherapyDoctor");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysioTherapyFactor", b =>
                {
                    b.HasOne("Hospital.Domain.Model.PhysTherFactGroup", "PhysTherFactGroup")
                        .WithMany("PhysioTherapyFactors")
                        .HasForeignKey("PhysTherFactGroupId");

                    b.Navigation("PhysTherFactGroup");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Staff", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital.Domain.Model.SurgeryOperation", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Hospital.Domain.Model.SurgeryGroup", "SurgeryGroup")
                        .WithMany("SurgeryOperations")
                        .HasForeignKey("SurgeryGroupId");

                    b.Navigation("Department");

                    b.Navigation("SurgeryGroup");
                });

            modelBuilder.Entity("Hospital.Domain.Model.SurgeryTherapyData", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Staff", "DiagnosisDoctor")
                        .WithMany()
                        .HasForeignKey("DiagnosisDoctorId");

                    b.HasOne("Hospital.Domain.Model.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("Hospital.Domain.Model.MedCard", "MedCard")
                        .WithMany("SurgeryTherapyDatas")
                        .HasForeignKey("MedCardId");

                    b.HasOne("Hospital.Domain.Model.SurgeryOperation", "SurgeryOperation")
                        .WithMany()
                        .HasForeignKey("SurgeryOperationId");

                    b.HasOne("Hospital.Domain.Model.Staff", "TherapyDoctor")
                        .WithMany()
                        .HasForeignKey("TherapyDoctorId");

                    b.Navigation("Diagnosis");

                    b.Navigation("DiagnosisDoctor");

                    b.Navigation("MedCard");

                    b.Navigation("SurgeryOperation");

                    b.Navigation("TherapyDoctor");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Test", b =>
                {
                    b.HasOne("Hospital.Domain.Model.TestType", "TestType")
                        .WithMany("Tests")
                        .HasForeignKey("TestTypeId");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestData", b =>
                {
                    b.HasOne("Hospital.Domain.Model.MedCard", "MedCard")
                        .WithMany("TestDatas")
                        .HasForeignKey("MedCardId");

                    b.HasOne("Hospital.Domain.Model.Staff", "StaffResult")
                        .WithMany()
                        .HasForeignKey("StaffResultId");

                    b.HasOne("Hospital.Domain.Model.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId");

                    b.Navigation("MedCard");

                    b.Navigation("StaffResult");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestNormalValue", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Test", "Test")
                        .WithMany("NormalValues")
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestTemplate", b =>
                {
                    b.HasOne("Hospital.Domain.Model.TestType", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Hospital.Domain.Model.Department", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestType", b =>
                {
                    b.HasOne("Hospital.Domain.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Department", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Diagnoses");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DiagnosisClass", b =>
                {
                    b.Navigation("DiagnosisGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DiagnosisGroup", b =>
                {
                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugClass", b =>
                {
                    b.Navigation("DrugSubClasses");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugGroup", b =>
                {
                    b.Navigation("DrugSubGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugSubClass", b =>
                {
                    b.Navigation("DrugGroups");
                });

            modelBuilder.Entity("Hospital.Domain.Model.DrugSubGroup", b =>
                {
                    b.Navigation("Drugs");
                });

            modelBuilder.Entity("Hospital.Domain.Model.MedCard", b =>
                {
                    b.Navigation("PharmacoTherapyDatas");

                    b.Navigation("PhysioTherapyDatas");

                    b.Navigation("SurgeryTherapyDatas");

                    b.Navigation("TestDatas");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysTherFactGroup", b =>
                {
                    b.Navigation("PhysioTherapyFactors");
                });

            modelBuilder.Entity("Hospital.Domain.Model.PhysTherMethodGroup", b =>
                {
                    b.Navigation("PhysTherMethods");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Staff", b =>
                {
                    b.Navigation("DoctorDestinations");

                    b.Navigation("Registrators");
                });

            modelBuilder.Entity("Hospital.Domain.Model.SurgeryGroup", b =>
                {
                    b.Navigation("SurgeryOperations");
                });

            modelBuilder.Entity("Hospital.Domain.Model.Test", b =>
                {
                    b.Navigation("NormalValues");
                });

            modelBuilder.Entity("Hospital.Domain.Model.TestType", b =>
                {
                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
